-- 迁移脚本：添加 DEPUTY_CHIEF_PHYSICIAN 到 doctors 表的 title ENUM
-- 执行此脚本以更新现有数据库

ALTER TABLE doctors 
MODIFY COLUMN title ENUM('RESIDENT', 'ATTENDING', 'ASSOCIATE_CHIEF', 'DEPUTY_CHIEF_PHYSICIAN', 'CHIEF') NOT NULL COMMENT '职称';

